### ISSUE TITLE
NoSuchFieldError with OptiNotFine

### ISSUE THREAD

**Issue by Ghostlyr** [Abastro/StellarAPI#1]
```
java.lang.NoSuchFieldError: field_78286_d
	at stellarapi.lib.gui.basicmodel.WrappedFontRenderer.func_78266_a(WrappedFontRenderer.java:39)
	at net.minecraft.client.gui.FontRenderer.func_78278_a(FontRenderer.java:264)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:523)
	at net.minecraft.client.gui.FontRenderer.func_78258_a(FontRenderer.java:636)
	at net.minecraft.client.gui.FontRenderer.func_85187_a(FontRenderer.java:390)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:369)
	at stellarapi.lib.gui.basicmodel.ModelFont.renderModel(ModelFont.java:65)
	at stellarapi.lib.gui.GuiRenderer.render(GuiRenderer.java:123)
	at stellarapi.lib.gui.text.GuiTextInternal.render(GuiTextInternal.java:269)
	at stellarapi.lib.gui.text.GuiTextField.render(GuiTextField.java:63)
	at stellarapi.lib.gui.list.GuiHasFixedList.render(GuiHasFixedList.java:134)
	at stellarapi.lib.gui.simple.GuiSimpleSpacingElement.render(GuiSimpleSpacingElement.java:64)
	at stellarapi.lib.gui.GuiContent.render(GuiContent.java:55)
	at stellarium.client.overlay.clock.OverlayClock.render(OverlayClock.java:222)
	at stellarapi.feature.gui.overlay.OverlayContainer.render(OverlayContainer.java:123)
	at stellarapi.feature.gui.overlay.OverlayHandler.renderGameOverlay(OverlayHandler.java:40)
	at stellarapi.StellarAPIClientForgeEventHook.renderGameOverlay(StellarAPIClientForgeEventHook.java:109)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_StellarAPIClientForgeEventHook_renderGameOverlay_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1362)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at stellarapi.lib.gui.basicmodel.WrappedFontRenderer.func_78266_a(WrappedFontRenderer.java:39)
	at net.minecraft.client.gui.FontRenderer.func_78278_a(FontRenderer.java:264)
	at net.minecraft.client.gui.FontRenderer.func_78255_a(FontRenderer.java:523)
	at net.minecraft.client.gui.FontRenderer.func_78258_a(FontRenderer.java:636)
	at net.minecraft.client.gui.FontRenderer.func_85187_a(FontRenderer.java:390)
	at net.minecraft.client.gui.FontRenderer.func_78276_b(FontRenderer.java:369)
	at stellarapi.lib.gui.basicmodel.ModelFont.renderModel(ModelFont.java:65)
	at stellarapi.lib.gui.GuiRenderer.render(GuiRenderer.java:123)
	at stellarapi.lib.gui.text.GuiTextInternal.render(GuiTextInternal.java:269)
	at stellarapi.lib.gui.text.GuiTextField.render(GuiTextField.java:63)
	at stellarapi.lib.gui.list.GuiHasFixedList.render(GuiHasFixedList.java:134)
	at stellarapi.lib.gui.simple.GuiSimpleSpacingElement.render(GuiSimpleSpacingElement.java:64)
	at stellarapi.lib.gui.GuiContent.render(GuiContent.java:55)
	at stellarium.client.overlay.clock.OverlayClock.render(OverlayClock.java:222)
	at stellarapi.feature.gui.overlay.OverlayContainer.render(OverlayContainer.java:123)
	at stellarapi.feature.gui.overlay.OverlayHandler.renderGameOverlay(OverlayHandler.java:40)
	at stellarapi.StellarAPIClientForgeEventHook.renderGameOverlay(StellarAPIClientForgeEventHook.java:109)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_29_StellarAPIClientForgeEventHook_renderGameOverlay_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
```

Installed last versions of StellarAPI and StellarSky for 1.7.10. Of other mods only OptiFIne Ultra D4.
Forge 1614.

**Comment by Ghostlyr** [comment]
Thanks, but it cause other error...  Maybe i'm incorrectly compiled source code, but i have crash on start:

```
cpw.mods.fml.common.LoaderException: java.lang.AbstractMethodError
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.AbstractMethodError
	at stellarapi.api.gui.overlay.OverlayRegistry$RegistryDelegate.<init>(OverlayRegistry.java:65)
	at stellarapi.api.gui.overlay.OverlayRegistry$RegistryDelegate.<init>(OverlayRegistry.java:51)
	at stellarapi.api.gui.overlay.OverlayRegistry.registerOverlay(OverlayRegistry.java:36)
	at stellarium.ClientProxy.preInit(ClientProxy.java:54)
	at stellarium.StellarSky.preInit(StellarSky.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 10 more
```

**Comment by Abastro** [comment]
I think something had been corrupted in the workspace, since that is something that can't happen.
Please wait for the release on Curse.
